const API='https://trendcart-wozq.onrender.com';const KEY='trendcart_cart';
function cart(){return JSON.parse(localStorage.getItem(KEY)||'[]')}
function save(c){localStorage.setItem(KEY,JSON.stringify(c));count()}
function count(){const n=cart().reduce((s,x)=>s+(Number(x.quantity)||1),0);const e=document.getElementById('cartCount');if(e)e.textContent=n}
function add(p){const c=cart();const size=document.querySelector(`input[name="size-${p.id}"]:checked`)?.value||'';if(['Clothes','Shoes'].includes(p.category)&&!size){alert('Please select a size');return}const k=p.id+'|'+size;const old=c.find(x=>x.key===k);if(old){if(old.quantity>=p.stock)return alert('Stock limit reached');old.quantity++}else c.push({...p,quantity:1,size,key:k});save(c);alert('Added to cart')}
function renderProducts(ps){const g=document.getElementById('productGrid');if(!ps.length){g.innerHTML='<p class="loading">No products found. Try another search.</p>';return}g.innerHTML=ps.map(p=>{let sizes=p.sizes||{};let opts=Object.entries(sizes).filter(([s,q])=>q>0).map(([s,q])=>`<label><input type="radio" name="size-${p.id}" value="${s}">${s}</label>`).join('');return `<article class="card"><div class="pic">${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:(p.category==='Shoes'?'👟':p.category==='Clothes'?'👕':'🛍️')}</div><h3>${p.name}</h3><div class="muted">${p.category} · Stock ${p.stock}</div><div class="price">₹${Number(p.price).toFixed(0)}</div>${opts?`<div class="sizes">${opts}</div>`:''}<button type="button" onclick='add(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Add to Cart</button></article>`}).join('')}
let products=[];
async function load(){try{const r=await fetch(API+'/api/products');if(!r.ok)throw Error('Server error');products=await r.json();renderProducts(products)}catch(e){document.getElementById('productGrid').innerHTML='<p class="loading">Products load नहीं हो पाए। कृपया थोड़ी देर बाद refresh करें.</p>'}}
function filter(){const q=(document.getElementById('searchBox')?.value||'').trim().toLowerCase();const cat=document.getElementById('categoryFilter')?.value||'';renderProducts(products.filter(p=>(!q||String(p.name).toLowerCase().includes(q)||String(p.category).toLowerCase().includes(q))&&(!cat||p.category===cat)))}
count();if(document.getElementById('productGrid')){document.getElementById('searchBox')?.addEventListener('input',filter);document.getElementById('categoryFilter')?.addEventListener('change',filter);load()}