const API='https://trendcart-wozq.onrender.com';const KEY='trendcart_cart';const WKEY='trendcart_wishlist';
function cart(){return JSON.parse(localStorage.getItem(KEY)||'[]')}
function wishlist(){return JSON.parse(localStorage.getItem(WKEY)||'[]')}
function save(c){localStorage.setItem(KEY,JSON.stringify(c));count()}
function saveWishlist(w){localStorage.setItem(WKEY,JSON.stringify(w));wishlistCount()}
function count(){const n=cart().reduce((s,x)=>s+(Number(x.quantity)||1),0);const e=document.getElementById('cartCount');if(e)e.textContent=n}
function wishlistCount(){const e=document.getElementById('wishlistCount');if(e)e.textContent=wishlist().length}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function isWish(id){return wishlist().some(x=>Number(x.id)===Number(id))}
function toggleWishlist(p){const w=wishlist();const i=w.findIndex(x=>Number(x.id)===Number(p.id));if(i>=0){w.splice(i,1)}else{w.push(p)}saveWishlist(w);if(document.getElementById('wishlistGrid'))renderWishlist();else if(typeof filter==='function')filter()}
function removeWishlist(id){saveWishlist(wishlist().filter(x=>Number(x.id)!==Number(id)));if(document.getElementById('wishlistGrid'))renderWishlist();else if(typeof filter==='function')filter()}
function add(p){const c=cart();const size=document.querySelector(`input[name="size-${p.id}"]:checked`)?.value||'';if(['Clothes','Shoes'].includes(p.category)&&!size){alert('Please select a size');return}const k=p.id+'|'+size;const old=c.find(x=>x.key===k);if(old){if(old.quantity>=p.stock)return alert('Stock limit reached');old.quantity++}else c.push({...p,quantity:1,size,key:k});save(c);alert('Added to cart')}
function buyNow(p){const size=document.querySelector(`input[name="size-${p.id}"]:checked`)?.value||'';if(['Clothes','Shoes'].includes(p.category)&&!size){alert('Please select a size');return}const item={...p,quantity:1,size,key:p.id+'|'+size};localStorage.setItem(KEY,JSON.stringify([item]));location.href='checkout.html?buynow=1'}
function renderProducts(ps){const g=document.getElementById('productGrid');const e=document.getElementById('wishlistCount');if(e)e.textContent=wishlist().length;if(!ps.length){g.innerHTML='<p class="loading">No products found. Try another search.</p>';return}g.innerHTML=ps.map(p=>{let sizes=p.sizes||{};let opts=Object.entries(sizes).filter(([s,q])=>q>0).map(([s,q])=>`<label><input type="radio" name="size-${p.id}" value="${s}">${s}</label>`).join('');const w=isWish(p.id);return `<article class="card"><div class="pic">${p.image?`<img src="${p.image}" alt="${escapeHtml(p.name)}" loading="lazy">`:(p.category==='Shoes'?'👟':p.category==='Clothes'?'👕':'🛍️')}<button class="wish-btn ${w?'wish-active':''}" type="button" aria-label="${w?'Remove from':'Add to'} wishlist" onclick='toggleWishlist(${JSON.stringify(p).replace(/'/g,"&#39;")})'>${w?'♥':'♡'}</button></div><h3>${escapeHtml(p.name)}</h3><div class="muted">${escapeHtml(p.category)} · Stock ${p.stock}</div><div class="price">₹${Number(p.price).toFixed(0)}</div>${opts?`<div class="sizes">${opts}</div>`:''}<button type="button" onclick='add(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Add to Cart</button><button class="secondary" type="button" onclick='buyNow(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Buy Now</button></article>`}).join('')}
let products=[];
async function load(){try{const r=await fetch(API+'/api/products');if(!r.ok)throw Error('Server error');products=await r.json();renderProducts(products)}catch(e){document.getElementById('productGrid').innerHTML='<p class="loading">Products load नहीं हो पाए। कृपया थोड़ी देर बाद refresh करें.</p>'}}
function filter(){const q=(document.getElementById('searchBox')?.value||'').trim().toLowerCase();const cat=document.getElementById('categoryFilter')?.value||'';renderProducts(products.filter(p=>(!q||String(p.name).toLowerCase().includes(q)||String(p.category).toLowerCase().includes(q))&&(!cat||p.category===cat)))}
count();wishlistCount();if(document.getElementById('productGrid')){document.getElementById('searchBox')?.addEventListener('input',filter);document.getElementById('categoryFilter')?.addEventListener('change',filter);load()}