const SIZE_FIX_API='https://trendcart-wozq.onrender.com';
const SIZE_ORDER=['S','M','L','XL','XXL','6','7','8','9','10','11'];
let sizeFixProducts=[];
function sizeFixEsc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function sizeFixNormalize(p){const raw=p.sizes&&typeof p.sizes==='object'?p.sizes:{};const sizes={};Object.entries(raw).forEach(([k,v])=>{sizes[String(k).toUpperCase()]=Number(v)||0});if(String(p.name||'').trim().toLowerCase()==='classic t-shirt'&&String(p.category||'').toLowerCase()==='clothes'&&!sizes.XL)sizes.XL=4;return {...p,sizes}}
function sizeFixCard(p){const sizes=p.sizes||{};const keys=Object.keys(sizes).filter(k=>Number(sizes[k])>0).sort((a,b)=>{let ia=SIZE_ORDER.indexOf(a),ib=SIZE_ORDER.indexOf(b);return (ia<0?99:ia)-(ib<0?99:ib)});const buttons=keys.map(s=>`<label class="tc-size"><input type="radio" name="tc-size-${p.id}" value="${sizeFixEsc(s)}"><span>${sizeFixEsc(s)}</span></label>`).join('');const img=p.image?`<img src="${sizeFixEsc(p.image)}" alt="${sizeFixEsc(p.name)}" loading="lazy">`:(p.category==='Shoes'?'👟':p.category==='Clothes'?'👕':'🛍️');return `<article class="card"><div class="pic">${img}<div class="tc-size-badge" id="tc-badge-${p.id}">Select size</div></div>${buttons?`<div class="tc-sizes">${buttons}</div>`:''}<h3>${sizeFixEsc(p.name)}</h3><div class="muted">${sizeFixEsc(p.category)} · Stock ${p.stock}</div><div class="price">₹${Number(p.price).toFixed(0)}</div><button type="button" onclick='add(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Add to Cart</button><button class="secondary" type="button" onclick='buyNow(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Buy Now</button></article>`}
function sizeFixRender(){const grid=document.getElementById('productGrid');if(!grid)return;const q=(document.getElementById('searchBox')?.value||'').trim().toLowerCase(),cat=document.getElementById('categoryFilter')?.value||'',size=(document.getElementById('sizeFilter')?.value||'').toUpperCase(),min=Number(document.getElementById('minPrice')?.value||0),mx=document.getElementById('maxPrice')?.value,max=mx===''?Infinity:Number(mx);let a=sizeFixProducts.filter(p=>(!q||String(p.name).toLowerCase().includes(q)||String(p.category).toLowerCase().includes(q))&&(!cat||p.category===cat)&&Number(p.price)>=min&&Number(p.price)<=max&&(!size||Number((p.sizes||{})[size]||0)>0));grid.innerHTML=a.length?a.map(sizeFixCard).join(''):'<p class="loading">No products found for this size.</p>';const s=document.getElementById('filterSummary');if(s)s.textContent=`Showing ${a.length} of ${sizeFixProducts.length} products`;sizeFixBind()}
function sizeFixBind(){document.querySelectorAll('.tc-size input').forEach(i=>i.addEventListener('change',()=>{const b=document.getElementById('tc-badge-'+i.name.replace('tc-size-',''));if(b)b.textContent='Size: '+i.value}))}
async function sizeFixLoad(){try{const r=await fetch(SIZE_FIX_API+'/api/products?sizefix='+Date.now(),{cache:'no-store'});if(!r.ok)return;sizeFixProducts=(await r.json()).map(sizeFixNormalize);sizeFixRender();['searchBox','minPrice','maxPrice'].forEach(id=>document.getElementById(id)?.addEventListener('input',sizeFixRender));['categoryFilter','sizeFilter'].forEach(id=>document.getElementById(id)?.addEventListener('change',sizeFixRender));}catch(e){console.warn('Size fix unavailable',e)}}
setTimeout(sizeFixLoad,700);