const express = require('express');
const crypto = require('crypto');
const { Pool } = require('pg');
const { buildFulfillmentJob, markReady } = require('./qikink-fulfillment');

const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.DATABASE_URL ? { rejectUnauthorized: false } : false });
function safeEqual(a,b){const x=Buffer.from(String(a||''));const y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function sign(v){return crypto.createHmac('sha256',process.env.ADMIN_SECRET||'missing-secret').update(v).digest('hex')}
function adminAuth(req,res,next){const h=req.headers.authorization||'';const parts=h.startsWith('Bearer ')?h.slice(7).split('.'):[];if(parts.length!==2||!process.env.ADMIN_SECRET||!safeEqual(parts[1],sign(parts[0])))return res.status(401).json({error:'Admin login required'});try{const p=JSON.parse(Buffer.from(parts[0],'base64url').toString());if(!p.u||Date.now()-p.t>86400000||!process.env.ADMIN_PASSWORD||p.u!==(process.env.ADMIN_USERNAME||'admin'))return res.status(401).json({error:'Admin session expired'});req.admin=p.u;next()}catch(_){return res.status(401).json({error:'Invalid admin token'})}}
async function prepareOrder(orderId){try{await buildFulfillmentJob(orderId);await markReady(orderId);return{status:'Ready for Submission'}}catch(e){await pool.query(`UPDATE orders SET qikink_status='Error',qikink_error=$1,qikink_synced_at=NOW() WHERE id=$2`,[String(e.message||e).slice(0,2000),Number(orderId)]).catch(()=>{});return{status:'Error',error:String(e.message||e)}}}
function addRoutes(app){if(app.__trendcartQikinkRoutes)return;app.__trendcartQikinkRoutes=true;app.get('/api/admin/qikink/health',adminAuth,async(req,res)=>{try{const r=await pool.query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER (WHERE qikink_status='Ready for Submission')::int AS ready,COUNT(*) FILTER (WHERE qikink_status='Error')::int AS errors FROM orders`);res.json({success:true,configured:Boolean(process.env.QIKINK_CLIENT_ID&&process.env.QIKINK_SECRET_KEY),...r.rows[0]})}catch(e){res.status(500).json({error:e.message||'Qikink health check failed'})}});app.get('/api/admin/qikink/orders',adminAuth,async(req,res)=>{try{const r=await pool.query(`SELECT id,customer_name,mobile,items,total,status,qikink_order_id,qikink_status,qikink_error,qikink_synced_at,created_at FROM orders ORDER BY id DESC LIMIT 200`);res.json({success:true,orders:r.rows})}catch(e){res.status(500).json({error:e.message||'Unable to load Qikink orders'})}});app.post('/api/admin/qikink/prepare/:id',adminAuth,async(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Invalid order ID'});const result=await prepareOrder(id);if(result.status==='Error')return res.status(400).json({success:false,...result});res.json({success:true,orderId:id,...result})});app.post('/api/admin/qikink/retry/:id',adminAuth,async(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Invalid order ID'});const result=await prepareOrder(id);if(result.status==='Error')return res.status(400).json({success:false,...result});res.json({success:true,orderId:id,...result})})}
const originalListen=express.application.listen;express.application.listen=function(...args){addRoutes(this);return originalListen.apply(this,args)};
const originalPost=express.application.post;express.application.post=function(path,...handlers){if(path==='/api/orders'||path==='/api/payment/verify'){const last=handlers[handlers.length-1];handlers[handlers.length-1]=async function(req,res,next){const originalJson=res.json.bind(res);res.json=function(body){const result=originalJson(body);if(body&&body.success&&body.orderId)Promise.resolve().then(()=>prepareOrder(Number(body.orderId))).catch(()=>{});return result};return last(req,res,next)}}return originalPost.call(this,path,...handlers)};
