const express=require('express');const helmet=require('helmet');const crypto=require('crypto');const path=require('path');const {Pool}=require('pg');const {spawn}=require('child_process');const {sendSupportReplyEmail}=require('./email');
const app=express();const PORT=Number(process.env.PORT||5000);const INTERNAL_PORT=PORT+1;const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
app.disable('x-powered-by');app.use(helmet());app.use(express.json({limit:'1mb'}));app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
function safeEqual(a,b){const x=Buffer.from(String(a||''));const y=Buffer.from(String(b||''));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
function adminUsername(){return String(process.env.ADMIN_USERNAME??process.env.ADMIN_ID??'admin').trim()}
function adminPassword(){return String(process.env.ADMIN_PASSWORD??process.env.ADMIN_PASS??'').trim()}
function adminSecret(){return String(process.env.ADMIN_SECRET??'')}
function configuredAdminValues(){const usernames=[process.env.ADMIN_USERNAME,process.env.ADMIN_ID,process.env.ADMIN_USER,process.env.ADMIN_LOGIN].filter(v=>v!==undefined&&v!==null&&String(v).trim()!=='').map(v=>String(v).trim());const passwords=[process.env.ADMIN_PASSWORD,process.env.ADMIN_PASS,process.env.ADMIN_PWD,process.env.ADMIN_LOGIN_PASSWORD].filter(v=>v!==undefined&&v!==null&&String(v).trim()!=='').map(v=>String(v).trim());return{usernames:[...new Set(usernames.length?usernames:['admin'])],passwords:[...new Set(passwords)]}}
function sign(v){return crypto.createHmac('sha256',adminSecret()||'missing-secret').update(v).digest('hex')}
// Admin authentication intentionally disabled per owner request.
function adminAuth(req,res,next){req.admin='admin';next()}
function clean(v,max){return String(v??'').trim().slice(0,max)}
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS support_tickets(id BIGSERIAL PRIMARY KEY,ticket_code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,mobile TEXT,order_id INTEGER,subject TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Open',admin_reply TEXT,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP)`)}
app.get('/api/admin/config-status',(req,res)=>{res.json({ok:true,loginRequired:false,adminLoginDisabled:true,serverTime:new Date().toISOString()})});
app.get('/api/admin/login-diagnostic',(req,res)=>{res.json({ok:true,loginRequired:false,adminLoginDisabled:true})});
app.get('/api/support/ticket',async(req,res)=>{try{const code=clean(req.query.ticket,40).toUpperCase();const email=clean(req.query.email,160).toLowerCase();if(!code||!email)return res.status(400).json({error:'Ticket ID and email are required'});const r=await pool.query("SELECT ticket_code,name,email,mobile,order_id,subject,message,status,admin_reply,created_at,updated_at FROM support_tickets WHERE ticket_code=$1 AND LOWER(email)=LOWER($2)",[code,email]);if(!r.rowCount)return res.status(404).json({error:'Ticket not found'});res.json({success:true,ticket:r.rows[0]})}catch(e){res.status(500).json({error:'Unable to load ticket'})}});
app.post('/api/support/tickets',async(req,res)=>{try{const name=clean(req.body?.name,80),email=clean(req.body?.email,160).toLowerCase(),mobile=clean(req.body?.mobile,20),subject=clean(req.body?.subject,120),message=clean(req.body?.message,2000),orderId=req.body?.order_id?Number(req.body.order_id):null;if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!subject||!message)return res.status(400).json({error:'Name, valid email, subject and message are required'});if(message.length<10)return res.status(400).json({error:'Message must be at least 10 characters'});if(orderId!==null&&(!Number.isInteger(orderId)||orderId<1))return res.status(400).json({error:'Invalid Order ID'});let code;for(let i=0;i<5;i++){code='TC-'+crypto.randomBytes(4).toString('hex').toUpperCase();try{const r=await pool.query('INSERT INTO support_tickets(ticket_code,name,email,mobile,order_id,subject,message) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING ticket_code,created_at',[code,name,email,mobile||null,orderId,subject,message]);return res.status(201).json({success:true,ticket:r.rows[0]})}catch(e){if(e.code!=='23505')throw e}}res.status(500).json({error:'Unable to create support ticket'})}catch(e){res.status(400).json({error:e.message||'Unable to create support ticket'})}});
app.get('/api/admin/support/tickets',adminAuth,async(req,res)=>{try{const status=clean(req.query.status,30);const params=[];let where='';if(status&&['Open','In Progress','Resolved'].includes(status)){params.push(status);where='WHERE status=$1'}const r=await pool.query(`SELECT id,ticket_code,name,email,mobile,order_id,subject,message,status,admin_reply,created_at,updated_at FROM support_tickets ${where} ORDER BY id DESC`,params);res.json({success:true,tickets:r.rows})}catch(e){res.status(500).json({error:'Unable to load support tickets'})}});
app.put('/api/admin/support/tickets/:id',adminAuth,async(req,res)=>{try{const id=Number(req.params.id);const status=clean(req.body?.status,30);const reply=clean(req.body?.admin_reply,3000);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Invalid ticket ID'});if(!['Open','In Progress','Resolved'].includes(status))return res.status(400).json({error:'Invalid ticket status'});const old=await pool.query('SELECT id,ticket_code,name,email,subject,admin_reply FROM support_tickets WHERE id=$1',[id]);if(!old.rowCount)return res.status(404).json({error:'Ticket not found'});const r=await pool.query('UPDATE support_tickets SET status=$1,admin_reply=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$3 RETURNING ticket_code,name,email,subject,status,admin_reply,updated_at',[status,reply||null,id]);const updated=r.rows[0];if(reply&&reply!==String(old.rows[0].admin_reply||'')){Promise.resolve().then(async()=>{try{const result=await sendSupportReplyEmail(updated);if(!result.sent)console.log('Support reply email not sent:',result.reason)}catch(e){console.error('Support reply email failed:',e.message||e)}})}res.json({success:true,ticket:updated,emailQueued:Boolean(reply&&reply!==String(old.rows[0].admin_reply||''))})}catch(e){res.status(400).json({error:e.message||'Unable to update support ticket'})}});
app.post('/api/admin/login',(req,res)=>res.json({success:true,loginRequired:false,adminLoginDisabled:true}));
const adminDir=path.join(__dirname,'../admin');
app.use('/admin',(req,res,next)=>{res.removeHeader('Content-Security-Policy');res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');next()});
app.get('/admin',(req,res)=>res.sendFile(path.join(adminDir,'index.html')));
app.get('/admin/',(req,res)=>res.sendFile(path.join(adminDir,'index.html')));
app.get('/admin/index.html',(req,res)=>res.sendFile(path.join(adminDir,'index.html')));
app.use('/admin',express.static(adminDir,{index:'index.html',etag:false,lastModified:false}));
const child=spawn(process.execPath,['customer-server.js'],{cwd:__dirname,env:{...process.env,PORT:String(INTERNAL_PORT)},stdio:'inherit'});child.on('exit',(code,signal)=>{console.error(`[STARTUP] customer-server exited. code=${code??'null'} signal=${signal||'none'}`);process.exit(code||1)});
process.on('uncaughtException',err=>{console.error('[STARTUP] uncaughtException:',err?.stack||err?.message||String(err));process.exit(1)});process.on('unhandledRejection',reason=>{console.error('[STARTUP] unhandledRejection:',reason?.stack||reason?.message||String(reason));process.exit(1)});
async function proxy(req,res){try{const headers={};for(const [k,v] of Object.entries(req.headers)){if(!['host','content-length','connection'].includes(k))headers[k]=v}const options={method:req.method,headers};if(!['GET','HEAD','OPTIONS'].includes(req.method))options.body=JSON.stringify(req.body||{});const upstream=await fetch(`http://127.0.0.1:${INTERNAL_PORT}${req.originalUrl}`,options);res.status(upstream.status);upstream.headers.forEach((v,k)=>{if(k!=='content-length')res.setHeader(k,v)});const buf=Buffer.from(await upstream.arrayBuffer());res.send(buf)}catch(e){console.error('[STARTUP] proxy/backend error:',e?.stack||e?.message||String(e));res.status(503).json({error:'Backend is starting. Please try again in a few seconds.'})}}
init().then(()=>app.listen(PORT,()=>console.log(`TrendCart support gateway running on port ${PORT}`))).catch(e=>{console.error('[STARTUP] Support database initialization failed:',e?.stack||e?.message||String(e));child.kill();process.exit(1)});